USE [PizzaItalia]
GO

/****** Object:  View [dbo].[QUANT_EXCLUSIONS_VIEW]    Script Date: 11/14/2022 8:54:57 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW  [dbo].[QUANT_EXCLUSIONS_VIEW] AS
SELECT EXCLUSIONS ,COUNT(EXCLUSIONS) QUANT_EXCLUSIONS FROM [dbo].[ingredients_exclusions] GROUP BY EXCLUSIONS
GO


